[package]
name = "aegis-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
aegis-resources = { path = "../../runtime/resources" }
aegis-notifications = { path = "../../integrations/slack" }
tokio = { workspace = true }
tonic = { workspace = true }
sqlx = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tokio-stream = { version = "0.1", features = ["sync"] }
async-trait = { workspace = true }
futures-core = { workspace = true }

aegis-config = { path = "../config" }
aegis-logs = { path = "../../runtime/logs" }
aegis-api = { path = "../api" }
aegis-control = { path = "../control" }
aegis-auth = { path = "../auth" }
rand_core = { version = "0.6", features = ["getrandom"] }
aegis-web = { path = "../web" }
aegis-event-bus = { path = "../event_bus" }
aegis-event-store = { path = "../event_store" }
aegis-plugins = { path = "../plugin" }
aegis-projection = { path = "../projection" }
aegis-scheduler = { path = "../scheduler" }
aegis-types = { path = "../types" }
aegis-process = { path = "../../runtime/process" }

[dev-dependencies]
tempfile = { workspace = true }
