[package]
name = "aegis-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }

aegis-config = { path = "../../core/config" }
aegis-api = { path = "../../core/api" }
aegis-types = { path = "../../core/types" }
aegis-engine = { path = "../../runtime/engine" }

