use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

fn default_max_retained_versions() -> usize {
    2
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct DaemonConfig {
    pub host: String,
    pub port: u16,
    pub database_path: PathBuf,
    pub log_level: String,
    #[serde(default = "default_max_retained_versions")]
    pub max_retained_versions: usize,
    /// Where releases, logs and build output live. Defaults to `~/.aegis`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data_dir: Option<PathBuf>,
}

impl DaemonConfig {
    /// The data directory, falling back to `$HOME/.aegis` (or `./.aegis` without a home).
    pub fn resolved_data_dir(&self) -> PathBuf {
        if let Some(dir) = &self.data_dir {
            return dir.clone();
        }
        match std::env::var_os("HOME").or_else(|| std::env::var_os("USERPROFILE")) {
            Some(home) => PathBuf::from(home).join(".aegis"),
            None => PathBuf::from(".aegis"),
        }
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, Default)]
pub struct Config {
    /// Optional so that a project-only `aegis.toml` (as generated by `aegis init`)
    /// still parses instead of silently falling back to defaults.
    #[serde(default)]
    pub daemon: DaemonConfig,
    #[serde(default)]
    pub web: WebConfig,
}

fn is_loopback_host(host: &str) -> bool {
    host == "localhost"
        || host
            .parse::<std::net::IpAddr>()
            .map(|ip| ip.is_loopback())
            .unwrap_or(false)
}

/// TLS certificate files for the HTTP API (PEM). Renewed files are picked up
/// without a restart.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Default)]
#[serde(default)]
pub struct TlsConfig {
    pub cert_path: Option<PathBuf>,
    pub key_path: Option<PathBuf>,
}

impl TlsConfig {
    pub fn enabled(&self) -> bool {
        self.cert_path.is_some() || self.key_path.is_some()
    }
}

/// The HTTP API (and, later, the dashboard) served by the daemon.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
#[serde(default)]
pub struct WebConfig {
    pub enabled: bool,
    pub host: String,
    pub port: u16,
    /// Public hostnames the API may be reached under (e.g. "aegis.example.com").
    /// Loopback names are always allowed.
    pub allowed_hosts: Vec<String>,
    /// A reverse proxy on this machine terminates HTTPS and forwards to
    /// Aegis on loopback. Enables Secure cookies and HSTS, and uses the
    /// proxy's X-Forwarded-For for login throttling.
    pub behind_proxy: bool,
    pub session_idle_minutes: u64,
    pub session_max_hours: u64,
    pub tls: TlsConfig,
}

impl Default for WebConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            host: "127.0.0.1".to_string(),
            port: 8420,
            allowed_hosts: Vec::new(),
            behind_proxy: false,
            session_idle_minutes: 120,
            session_max_hours: 24,
            tls: TlsConfig::default(),
        }
    }
}

impl WebConfig {
    /// Whether clients reach the API over HTTPS (directly or via the proxy).
    pub fn https(&self) -> bool {
        self.tls.enabled() || self.behind_proxy
    }

    /// Refuses configurations that would expose the API unsafely:
    /// - a non-loopback address without TLS (passwords and session cookies
    ///   would cross the network in clear text);
    /// - public access without `allowed_hosts` (needed for Host checks);
    /// - half-configured TLS.
    pub fn validate(&self) -> Result<(), anyhow::Error> {
        if self.tls.cert_path.is_some() != self.tls.key_path.is_some() {
            anyhow::bail!("web.tls needs both cert_path and key_path");
        }
        if !is_loopback_host(&self.host) && !self.tls.enabled() {
            anyhow::bail!(
                "web.host = \"{}\" is not a loopback address, and web.tls is not configured. \
                 Exposing the API without TLS would send passwords and session cookies in clear text. \
                 Either set [web.tls] cert_path/key_path, or keep web.host = \"127.0.0.1\" and put a \
                 reverse proxy such as Caddy in front with web.behind_proxy = true.",
                self.host
            );
        }
        if (self.behind_proxy || !is_loopback_host(&self.host)) && self.allowed_hosts.is_empty() {
            anyhow::bail!(
                "web.allowed_hosts must list the public hostname(s) of the API (e.g. [\"aegis.example.com\"]) \
                 when it is reachable from outside this machine"
            );
        }
        if self.session_idle_minutes == 0 || self.session_max_hours == 0 {
            anyhow::bail!("web.session_idle_minutes and web.session_max_hours must be positive");
        }
        Ok(())
    }
}

impl DaemonConfig {
    /// The gRPC API has no authentication and is used by the local CLI, so
    /// it must stay on loopback. Remote access goes through the HTTP API.
    pub fn validate(&self) -> Result<(), anyhow::Error> {
        if !is_loopback_host(&self.host) {
            anyhow::bail!(
                "daemon.host = \"{}\" is not a loopback address. The gRPC API is unauthenticated and \
                 only serves the local CLI; use the HTTP API (with a login or API token) for remote access, \
                 or an SSH tunnel.",
                self.host
            );
        }
        Ok(())
    }
}

impl Default for DaemonConfig {
    fn default() -> Self {
        Self {
            host: "127.0.0.1".to_string(),
            port: 50051,
            database_path: PathBuf::from("aegis.db"),
            log_level: "info".to_string(),
            max_retained_versions: 2,
            data_dir: None,
        }
    }
}

impl Config {
    /// Loads the configuration from the specified path.
    pub fn load_from_file<P: AsRef<Path>>(path: P) -> Result<Self, anyhow::Error> {
        let content = std::fs::read_to_string(path)?;
        let config: Config = toml::from_str(&content)?;
        Ok(config)
    }

    /// Loads the file if it exists (defaults otherwise). Unlike
    /// [`Config::load_or_default`], a file that exists but doesn't parse is
    /// an error, so a typo can't silently disable settings.
    pub fn load<P: AsRef<Path>>(path: P) -> Result<Self, anyhow::Error> {
        let path = path.as_ref();
        if !path.exists() {
            return Ok(Self::default());
        }
        Self::load_from_file(path)
            .map_err(|e| anyhow::anyhow!("Invalid configuration in {}: {}", path.display(), e))
    }

    /// Loads the configuration from the specified path or returns the default configuration if loading fails.
    pub fn load_or_default<P: AsRef<Path>>(path: P) -> Self {
        Self::load_from_file(path).unwrap_or_default()
    }
}

// ----------------------------------------------------
// Project configuration (the [project]/[build]/[deploy]/[env] sections)
// ----------------------------------------------------

#[derive(Debug, Serialize, Deserialize, Clone, Default, PartialEq)]
pub struct ProjectSection {
    pub id: Option<String>,
    pub name: Option<String>,
    pub runtime: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone, Default, PartialEq)]
pub struct BuildSection {
    pub install_command: Option<String>,
    pub build_command: Option<String>,
    pub test_command: Option<String>,
    pub start_command: Option<String>,
    /// Upper bound for each of install/build/test.
    pub timeout_secs: Option<u64>,
}

#[derive(Debug, Serialize, Deserialize, Clone, Default, PartialEq)]
pub struct DeploySection {
    pub strategy: Option<String>,
    /// Port the app listens on; exported to the app as `PORT`.
    pub port: Option<u16>,
    /// `http://host:port/path` or `host:port`. Empty means "process stays up".
    pub health_check_url: Option<String>,
    /// How long a freshly started release may take to become healthy.
    pub health_check_timeout_secs: Option<u64>,
    pub max_retained_versions: Option<usize>,
    /// Grace period between SIGTERM and SIGKILL when stopping the app.
    pub drain_timeout_secs: Option<u64>,
    /// `always` (default), `on-failure` or `never`.
    pub restart_policy: Option<String>,
}

/// The per-project part of `aegis.toml`. Every field is optional so partial
/// or hand-written files still parse; callers fill gaps from runtime detection.
#[derive(Debug, Serialize, Deserialize, Clone, Default, PartialEq)]
pub struct ProjectFile {
    #[serde(default)]
    pub project: ProjectSection,
    #[serde(default)]
    pub build: BuildSection,
    #[serde(default)]
    pub deploy: DeploySection,
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub env: BTreeMap<String, String>,
}

impl ProjectFile {
    pub fn parse(content: &str) -> Result<Self, anyhow::Error> {
        Ok(toml::from_str(content)?)
    }

    pub fn load<P: AsRef<Path>>(path: P) -> Result<Self, anyhow::Error> {
        Self::parse(&std::fs::read_to_string(path)?)
    }

    /// Loads `aegis.toml` from a directory, returning `None` if it doesn't exist.
    pub fn load_from_dir(dir: &Path) -> Result<Option<Self>, anyhow::Error> {
        let path = dir.join("aegis.toml");
        if !path.exists() {
            return Ok(None);
        }
        Self::load(path).map(Some)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    #[test]
    fn test_default_config() {
        let config = Config::default();
        assert_eq!(config.daemon.host, "127.0.0.1");
        assert_eq!(config.daemon.port, 50051);
        assert_eq!(config.daemon.log_level, "info");
    }

    #[test]
    fn test_load_from_file() {
        let mut temp_file = NamedTempFile::new().unwrap();
        let toml_content = r#"
[daemon]
host = "0.0.0.0"
port = 9000
database_path = "test.db"
log_level = "debug"
data_dir = "/srv/aegis"
"#;
        temp_file.write_all(toml_content.as_bytes()).unwrap();

        let config = Config::load_from_file(temp_file.path()).unwrap();
        assert_eq!(config.daemon.host, "0.0.0.0");
        assert_eq!(config.daemon.port, 9000);
        assert_eq!(config.daemon.database_path.to_str().unwrap(), "test.db");
        assert_eq!(config.daemon.log_level, "debug");
        assert_eq!(
            config.daemon.resolved_data_dir(),
            PathBuf::from("/srv/aegis")
        );
    }

    #[test]
    fn test_load_project_only_file_uses_daemon_defaults() {
        let mut temp_file = NamedTempFile::new().unwrap();
        let toml_content = r#"
[project]
id = "abc"
name = "demo"

[deploy]
strategy = "GracefulSwitch"
"#;
        temp_file.write_all(toml_content.as_bytes()).unwrap();

        let config = Config::load_from_file(temp_file.path()).unwrap();
        assert_eq!(config.daemon.port, 50051);
        assert_eq!(config.daemon.host, "127.0.0.1");
    }

    #[test]
    fn test_web_config_exposure_rules() {
        let config: Config = toml::from_str("[web]\nenabled = true\n").unwrap();
        assert!(config.web.enabled);
        assert_eq!(config.web.port, 8420);
        assert!(config.web.validate().is_ok());
        assert!(!config.web.https());
        assert!(!Config::default().web.enabled);

        let web = |toml_src: &str| toml::from_str::<Config>(toml_src).unwrap().web;

        // Public bind without TLS: refused.
        assert!(
            web("[web]\nhost = \"0.0.0.0\"\nallowed_hosts = [\"a.example\"]\n")
                .validate()
                .is_err()
        );
        // Public bind with TLS but no allowed_hosts: refused.
        let tls = "[web.tls]\ncert_path = \"c.pem\"\nkey_path = \"k.pem\"\n";
        assert!(web(&format!("[web]\nhost = \"0.0.0.0\"\n{tls}"))
            .validate()
            .is_err());
        // Public bind with TLS and allowed_hosts: fine.
        let ok = web(&format!(
            "[web]\nhost = \"0.0.0.0\"\nallowed_hosts = [\"a.example\"]\n{tls}"
        ));
        assert!(ok.validate().is_ok());
        assert!(ok.https());
        // Proxy mode requires allowed_hosts and implies HTTPS.
        assert!(web("[web]\nbehind_proxy = true\n").validate().is_err());
        let proxy = web("[web]\nbehind_proxy = true\nallowed_hosts = [\"a.example\"]\n");
        assert!(proxy.validate().is_ok());
        assert!(proxy.https());
        // Half-configured TLS.
        assert!(web("[web.tls]\ncert_path = \"c.pem\"\n")
            .validate()
            .is_err());

        for ok in ["127.0.0.1", "::1", "localhost"] {
            let d = DaemonConfig {
                host: ok.to_string(),
                ..DaemonConfig::default()
            };
            assert!(d.validate().is_ok());
        }
        let d = DaemonConfig {
            host: "0.0.0.0".to_string(),
            ..DaemonConfig::default()
        };
        assert!(d.validate().is_err(), "gRPC must stay on loopback");
    }

    #[test]
    fn test_load_reports_parse_errors() {
        let mut bad = NamedTempFile::new().unwrap();
        bad.write_all(b"[web]\nenabled = \"yes please\"\n").unwrap();
        assert!(Config::load(bad.path()).is_err());
        assert!(Config::load("/definitely/missing.toml").is_ok());
    }

    #[test]
    fn test_project_file_parsing() {
        let file = ProjectFile::parse(
            r#"
# Generated automatically by Aegis Detector Pipeline
[project]
id = "01a0e66a-2697-73c0-bff5-3346fccc6ad3"
name = "node-app"
runtime = "Node.js"

[build]
build_command = "npm run build"
start_command = "npm start"

[deploy]
strategy = "GracefulSwitch"
port = 3000
health_check_url = "http://127.0.0.1:3000/health"
health_check_timeout_secs = 5

[env]
NODE_ENV = "production"

[daemon]
port = 50051
host = "127.0.0.1"
database_path = "aegis.db"
log_level = "info"
"#,
        )
        .unwrap();
        assert_eq!(
            file.project.id.as_deref(),
            Some("01a0e66a-2697-73c0-bff5-3346fccc6ad3")
        );
        assert_eq!(file.build.start_command.as_deref(), Some("npm start"));
        assert_eq!(file.build.install_command, None);
        assert_eq!(file.deploy.port, Some(3000));
        assert_eq!(file.env.get("NODE_ENV").unwrap(), "production");

        assert_eq!(ProjectFile::parse("").unwrap(), ProjectFile::default());
    }
}
