[package]
name = "aegis-notifications"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
aegis-types = { path = "../../core/types" }
aegis-plugins = { path = "../../core/plugin" }
