name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libsqlite3-dev
      - name: Run Cargo Check
        run: cargo check --workspace --all-targets

  clippy:
    name: Linter (Clippy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libsqlite3-dev
      - name: Run Cargo Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

  test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libsqlite3-dev
      - name: Run Workspace Tests
        run: cargo test --workspace --all-targets

  fmt:
    name: Code Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check Formatting
        run: cargo fmt --all -- --check
